spring:
  application:
    name: MultimediaInhalte

  datasource:
    url: jdbc:mysql://localhost:3307/multimedia
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 0

